export { watchHeader, type WatchHeaderOptions } from './header'
export { initReveal, splitLines } from './reveal'
export { initCircleHero, type CircleHeroOptions } from './circle-hero'
export { createImageWipe, type ImageWipe } from './image-wipe'
export { initMarquee, type MarqueeOptions } from './marquee'
export { initCurtain, type CurtainOptions } from './curtain'
export { useCircleHero, useCurtain, useHeaderWatch, useImageWipe, useMarquee, useReveal } from './react'
